### ISSUE TITLE
Using shared login table

### ISSUE THREAD

**Issue by lRaikeNl** [NoCode-NoLife/melia#158]
Many platforms use one single login / account table for account information.
(This would be a feature)
How about making a shared table on a specific schema accessable for the login server?
I'd try to implement it when I got time. Just wanted to ask if thats a good idea.

**Comment by exectails** [comment]
Don't we already have a single account table? What exactly are you proposing we change?

**Comment by exectails** [comment]
Oh, that's what you mean. How would you approach that? Different applications might have vastly different requirements and conventions, such as different password hashing methods. The way I've done this in the past was to create accounts for all services, synchronizing the data between them.

**Comment by lRaikeNl** [comment]
I'd achieve this by adding an option at the database config file. Maybe an option for "use different login source" boolean,
table name
database name
login etc.

and if the encryption varies specify default encryption types such as hash etc.
and only specify table columns if they're different from the original.
for example: authority : `level` int(11)

**Comment by exectails** [comment]
The idea is interesting, but I'm unsure how well that would actually work in the real world. Password hashes in particular will probably be tricky, since you don't even get raw passwords from the client, but MD5 hashes. If your other system used BCrypt hashes from raw passwords for example, how would you make those two compatible?

**Comment by celophi** [comment]
> one account via website and use this account across the other applications instead of creating a new account for each emulator.

This sounds really out of scope for what the project is about.

> If your other system used BCrypt hashes from raw passwords for example, how would you make those two compatible?

I did this just by hashing MD5 then hashing BCrypt which works fine.

**Comment by exectails** [comment]
Sure, but then you most likely have to modify your other system, which kinda defeats the point.

**Comment by celophi** [comment]
> Sure, but then you most likely have to modify your other system, which kinda defeats the point.

Yes. There is no way around that. You would need to have some compatibility layer where you hash twice to check if the raw password is the same for both systems. So, if you go raw -> bcrypt, you need to do that verification. Additionally, also the raw -> md5 -> bcrypt verification. It is quite annoying.

**Comment by exectails** [comment]
Mhm, that's why I said the passwords are gonna be tricky, because there are cases that will simply not work without modifying some of the systems, and since we're talking about server emulators, where you might not even have control over what you get from the clients, some combinations might actually be near impossible.

**Comment by lRaikeNl** [comment]
I guess you are right. Another option would be an other password column or implementing plugins to not change the source. I guess this discussion can be closed then.
