### ISSUE TITLE
Anyone interested in continuing this project?

### ISSUE THREAD

**Issue by Adephx** [NoCode-NoLife/melia#164]
Wonder if anyone would be willing to tackle this project again, or at least update the project to work with the latest client? If someone can make the basic interactions to work, such as login, char select, basic movement, I could try to tackle other systems once I understand how the basics works. I have no experience with server emulation, but I'm somewhat decent with C#.

I can also try to tackle the problem on my own, as long as someone gives me a quick tutorial on how to approach the issue of solving compatibility between the ToS client and the Emulator.

**Comment by ovflowd** [comment]
> But the current client is fine as it is.

Differently from Ragnarok, the ToS client is bounded to Steam and usually it auto-updates.

In the RO times, we had patchers create custom clients by replacing variables as we desired (Such as Wallpapers, The Name Servers/IP Addresses to connect and et cetera).

We might also patch it to bypass Steam check. Not to mention that Username and Password are completely done by Steam, so there's no feature for Creating Accounts. Another alternative is "Creating Accounts Online" and then using Steam itself to validate that the username matches the one you claim it to be.

**Comment by exectails** [comment]
Actually, ToS does have a normal login screen, you just have to instruct the client to use it, by making it download a certain modified text file from a web server. Zemyna can do that automatically, or you can modify the client.xml and either use Melia's web server or your own to serve the static __Config.txt. Once you have that, you can create accounts on Melia similar to how you can on eAthena, with `new//account_name` (instead of `account_name_M/F`).

ToS using Steam doesn't change much about how you get or update the client. It still uses a classic patcher, just like RO did, which you might use if you do want to update the client to the latest version, just like many of us did for RO. Private servers would want their own custom patchers of course, but that doesn't affect the work on Melia. And you don't have to auto-update the game of course.

**Comment by ovflowd** [comment]
> Actually, ToS does have a normal login screen, you just have to instruct the client to use it, by making it download a certain modified text file from a web server. Zemyna can do that automatically, or you can modify the client.xml and either use Melia's web server or your own to serve the static __Config.txt. Once you have that, you can create accounts on Melia similar to how you can on eAthena, with new//account_name (instead of account_name_M/F).

That's mind blowing. Didn't know that ToS supported that. Probably kTOS uses normal login/password, right?

The new//acount_name thingy is nice :)

> ToS using Steam doesn't change much about how you get or update the client. It still uses a classic patcher, just like RO did, which you might use if you do want to update the client to the latest version

So basically if we patch the patcher we should be fine. Okay.

**Comment by exectails** [comment]
Either that or write your own patcher. ToS uses a very simple patch system, where new IPF files simply take precedence over older ones. All you have to do is download new IPF files and throw them into the patch folder.
