### ISSUE TITLE
Upgrade .NET SDK to v4.6.2

### ISSUE THREAD

**Issue by ovflowd** [NoCode-NoLife/melia#180]
Since .NET 4.5 is already outdated and deprecated by official means, we're going to upgrade to the latest .NET SDK before .NET 5.0.

This should be a flawless upgrade and not introduce any bugs.

**Comment by exectails** [comment]
I don't think we should update to 4.8 yet, because that will potentially break compatibility with IDEs, compilers, VMs, and tools that could otherwise use Melia's assemblies and code. Using the latest version has been a problem with Linux in particular in the past, where you don't always get the latest version of Mono out-of-the-box. I would suggest sticking to a common denominator for now, that will work in most cases. We don't gain much by updating to 4.8, but it would potentially create more hassle for users.

**Comment by ovflowd** [comment]
I see, haven't thought about that. What if we update to .NET 4.7 or .NET 4.6.2?

Only .NET 4.5.2, 4.6.0, 4.6.1 are marked to EOL on April 2022. https://devblogs.microsoft.com/dotnet/net-framework-4-5-2-4-6-4-6-1-will-reach-end-of-support-on-april-26-2022/

Mono supports .NET 4.7 and .NET 4.6 and it comes bundled with them. All the stable releases come with it, and Ubuntu and major Linux distributions ship them.

If we update to .NET 4.7 we'd have C# 7.0 support, and if we update to .NET 4.6.2 we still will get C# 6.0 Roslyn support. It is important to mention that the performance gains on .NET 4.6.2 compare to .NET 4.5 are immense.

**Comment by ovflowd** [comment]
Notes on Mono compatibility: https://www.mono-project.com/docs/about-mono/compatibility/

Notes on changelog of .NET: https://docs.microsoft.com/en-us/dotnet/framework/whats-new/

**Comment by exectails** [comment]
Note that that page is about the latest version of Mono, 6.12. For example, Ubuntu 18.04 LTS has Mono 4.6.2.7 in the default repositories, which uses .NET 4.5 and C# 6 afaik. Older, but still maintained versions of Debian, such es 9, use the same version. Maybe we could go with 4.6.2? That would still give us the last 3 Debian Versions.

**Comment by ovflowd** [comment]
Sure thing. Let's go with 4.6.2 which supports Roslyn (Which has super cool features). And it's also not affected by the EOL. Hold tight ;)
