### ISSUE TITLE
Add client scripting API

### ISSUE THREAD

**Issue by exectails** [NoCode-NoLife/melia#208]
Sending Lua scripts to the client for execution, aka "Client Scripting", is a very useful way to change the client's behavior, as quite a few core systems and the entire UI are running on Lua.

Right now we're just sending raw scripts to the client with very little structure behind them, but as our requirements grow, we'll want a couple creature comforts, such as having a standardized way of communicating back and forth with the client, creating and modifying UIs, logging messages, etc, etc. For this purpose, we'll add systems to both Lua and C# sides. The Lua code will have to be sent before all other client scripts, so they can utilize it, and on the server we should consider making (some of) the API calls asynchronous, to get a smooth communication experience.

There is no clear plan behind this yet, aside from knowing that we'll want this. It might also be beneficial to scour modding communities to see what's already out there in terms of customization via scripts.

**Comment by exectails** [comment]
Moved to the next milestone because this needs more time in the oven as we learn more about what the API needs to do for us. For the time being it now provides several functions that make it easier to customize the client's behavior, log messages, or communicate large amounts of data to the client.

**Comment by Voudi** [comment]
Using this, I am envisioning the design of an ingame 'admin ui panel', in which you could customize your server from inside your client, using no code at all, easing the process of actually designing the game world for 'creative' players significantly.

This would, however, require an easy way to invoke custom server commands from client side LUA, because we need to access the database in some unique ways.

Some ideas would be:
- Adjusting basic server settings ('meta settings' like droprate or exp modification)
- GM settings (player list and commands as buttons like warp, mute, freeze, kill)
- Map settings (setting up spawn points, spawn zones/waymarks/surprise attacks, warps)
- Mob settings (altering mobs hp, skills, respawn time)
- Exporting/Importing settings to other clients

You could also go full-double-circle: on top of custom server commands, you could inject LUA code back into the server database, allowing the creation of 'behaviour scripts' for each entity, be it an item, mob, or skill. This would also enable the creation of a 'cinematic designer' using LUA.

All of this is taking into account the authority level of its user, of course.

**Comment by exectails** [comment]
That's an interesting idea, though also an ambitious one, and I have to wonder whether this would actually require an API. You could put all that into the client and then instruct the server to make the changes, but I don't quite see what the client is contributing in this equation. Wouldn't it be much easier to write a control panel outside of the client, using a windows or web interface for example? That way you're cutting out the server as the middleman, you don't have to use the game's UI system, and you remove any potential limitations an API brings, such as only being able to change what was actually made changeable.

**Comment by exectails** [comment]
After improving the communication API slightly and adding a simple way to modify the system menu at the bottom right of the screen I will consider this issue to be completed for the moment. The API is there and can be improved upon as we progress.
