### ISSUE TITLE
Add Weaknesses and Damage Modifiers

### ISSUE THREAD

**Issue by exectails** [NoCode-NoLife/melia#235]
We currently aren't handling the different damage modifiers yet, such as races, elements, sizes, attack types, etc. These need to be added as part of the damage calculations, which will require researching the different modifiers, potentially adding new data for them to monsters and skills (this should be done by me), and finally adding all of it to the scriptable functions where we calculate the skill damages.

- [x] Race (Mutant, Beast, Plant, etc)
- [x] Elements (Fire, Ice, etc)
- [x] Armors (Slash, Pierce, etc)
- [x] Sizes (S, M, etc)

**Comment by exectails** [comment]
Thanks for additional information. The attacks in the second image presumably correspond to the skills' attack type in our data, though there are curiously more types and materials than the ones listed there. I wonder if those are all combinations. Also feels weird that ghost doesn't change anything. And are there no negative modifiers? 🤔

**Comment by felipecastagnarodecarvalho** [comment]
All those are outdate.
I guess the only source we can really consider is the client shared scripts.

**Comment by kenedos** [comment]
> ![image](https://user-images.githubusercontent.com/29080604/251830323-b65d4625-7abf-438d-93e0-d27fa7c138b0.png)
> 
> ![image](https://user-images.githubusercontent.com/29080604/251830498-73329a5b-5238-4e75-935a-c8b52c66913b.png)
> 

Those images are from the "renewal" ToS version, where they basically completely killed the damage bonus per type system. On the new system there is 5% more dmg on the these types as shown, and no penalties.

On the old system, however, there were more convincing bonuses and penalties:

![image](https://github.com/NoCode-NoLife/melia/assets/91282765/beff7dff-e1ca-4608-b32b-35daf6bd341b)

![image](https://github.com/NoCode-NoLife/melia/assets/91282765/730a1126-4a5c-46f4-8578-54b52e66ce58)

Note that attacks are either "physical" or "magical". For physical ones, there is slash, stab and hit (according to weapon & skill type, self-explanatory). For magical ones, they could had an elemental (fire, ice, etc) or just be "magic".

They also took the same idea from RO of having 100% extra dmg from lightning to ice, and 100% from holy to dark and from dark to holy.

**Comment by exectails** [comment]
Mhm, that looks _much_ more like what I would've expected. We definitely gotta add both.

**Comment by exectails** [comment]
Here's some data from a 2018 client (skill_attribute.ies).

|               | Fire  | Ice   | Lightning | Earth | Poison | Dark | Holy | Soul |
|---------------|------:|------:|----------:|------:|-------:|-----:|-----:|-----:|
| **Fire**      | -25   | 0     | 0         | +50   | 0      | 0    | 0    | 0    |
| **Ice**       | +50   | -25   | 0         | 0     | 0      | 0    | 0    | 0    |
| **Lightning** | 0     | +50   | -25       | 0     | 0      | 0    | 0    | 0    |
| **Earth**     | 0     | 0     | +50       | -25   | 0      | 0    | 0    | 0    |
| **Poison**    | +12.5 | +12.5 | +12.5     | +12.5 | -25    | 0    | 0    | 0    |
| **Dark**	    | 0     | 0     | 0         | 0     | 0      | -25  | +50  | 0    |
| **Holy**      | 0     | 0     | 0         | 0     | 0      | +50  | -25  | 0    |
| **Soul**      | 0     | 0     | 0         | 0     | 0      | +25  | +25  | +50  |


|            | Cloth | Leather | Iron  | Chain | Ghost |
|------------|------:|--------:|------:|------:|------:|
| **Slash**  | +25   | 0       | 0     | 0     | 0     |
| **Aries**  | 0     | +25     | 0     | 0     | 0     |
| **Strike** | 0     | 0       | +25   | 0     | 0     |
| **Magic**  | 0     | 0       | 0     | 0     | +25   |
| **Arrow**  | +12.5 | +12.5   | 0     | 0     | 0     |
| **Gun**	 | +12.5 | +12.5   | 0     | 0     | 0     |
| **Cannon** | 0     | 0       | +25   | 0     | 0     |

**Comment by kenedos** [comment]
They adjusted the damage bonus values a few times, probably due to how "inflexible" your damage type is in this game.

Note how they removed the slash/pierce/strike -50% penalty when damaging ghosts. This was one of the first things they did. The change was mostly to accommodate physical damage classes (like swordman) dealing half damage all the time to ghost mobs.

Imbuements/Enchants wouldn't change your damage type at all. For example, if a pyromancer casted enchant fire on your swordman, you would gain 1 extra line of fire damage on your basic attacks, but your skills would continue being slash/pierce/strike. Unless you had a "basic attack focused build", enchants would be useless.

In ToS most of levels were gained through questing, so it's not like you could choose your targets. If you were coupled with a disadvantageous property boss, it could become nearly impossible to progress further.

I personally liked the old system, but it was annoying not being able to change your damage type. I would love to see a custom option where you can change your physical damage type to any element while retaining it's damage type (like slash+fire) so that not only magical damage is able to have elemental properties. Would be pretty cool to have custom gems/cards in future that would be able to change your weapon's element, for example, so you can have different endowed weapons.

**Comment by exectails** [comment]
Definitely sounds like they didn't think that system through, and then hotfixed it by essentially making it completely useless. Maybe it would've been less of a problem if they hadn't chosen to embrace the theme park MMO structure midway through development 🙄 Well, one more thing we can improve.

**Comment by exectails** [comment]
The basic functionality has now been implemented, though how exactly, if at all, this works for players when attacked by monsters is yet to be figured out. I will still consider this to be complete for the moment though, since I'm not aware of any more data. We'll just have to continue to refine it.
