### ISSUE TITLE
Increase the number of slots in Skilltree?

### ISSUE THREAD

**Issue by Terotrous** [NoCode-NoLife/melia#274]
Currently, we can change out the skills a class can learn by changing the entries in the skill tree, but it's not possible to increase the total number of skills via any method currently known.  Is there a way this can be done?

**Comment by exectails** [comment]
To the best of my knowledge there is currently no way to modify an IES object's class id or class name from the server, which would be necessary to overwrite existing skill tree entries from other classes, to use them for the ones we're interested in. It also does not appear to be possible to insert new objects either.

One option might be to utilize client scripting to inject the skills into the results of the various functions the client uses to access the skill data. We employ a similar tactic with NPC shops to create custom shops from the server. However, with skills this would be a bit more tedious, and we didn't do any research into whether this would work all the way yet. Because while you can make the skills appear in the UI, it's unclear whether the client would let you use them if only the Lua environment knows about them.

The only straight forward way we currently have to modify the skill tree is actual client modification, where you simply modify the skilltree.ies however you see fit.

**Comment by exectails** [comment]
Well, my brain wouldn't leave me alone, so I took a closer look. And the result is...

https://github.com/NoCode-NoLife/melia/assets/5593920/3fe614ad-0e57-4ed5-bdb1-d53b22e7eb41

There's a couple little hurdles along the way, but yes, it is possible to inject a new skill into the Lua skill handling, and the client will dutifully use it if the server gives its okay. I guess this will our path toward rearranging the skill tree for pre-ReBuild.

**Comment by Terotrous** [comment]
Interesting stuff.  It turns out that the reason it didn't work through IES editing was an error in the IPFBrowser with saving IPF files that I fixed, so it can now be done via either method.
